//// DO NOT EDIT THIS FILE

#ifndef Matchmaker_Included
#define Matchmaker_Included

#include "BipartiteGraph.h"

/**
 * Given a bipartite graph, returns a maximum matching in that graph. If there are multiple
 * equally large maximum matchings, you can return any one of them.
 *
 * @param graph The graph in question.
 * @return One of its maximum matchings.
 */
Matching matchmake(const BipartiteGraph& graph);

#endif
