//// DO NOT EDIT THIS FILE

#ifndef Optimizer_Included
#define Optimizer_Included

#include "TaskGroup.h"
#include "hashset.h"

/**
 * Given a process, returns a list of all the tasks in that process that, if optimized, would
 * lead to the overall completion time improving.
 *
 * @param process The process in question.
 * @return A set of all the tasks that, if optimized, would improve the overall completion time.
 */
HashSet<Task *> optimizationCandidatesFor(const TaskGroup& process);

#endif
