//// DO NOT EDIT THIS FILE

#ifndef Waterlevel_Included
#define Waterlevel_Included

#include "Floodplain.h"

/**
 * Given a floodplain and an altitude, returns a Grid<bool> indicating whether each cell
 * is under water. Cells under water are marked true; cells above water are marked false.
 *
 * Remember that water can only flow in cardinal directions (up, down, left, and right),
 * not diagonally.
 *
 * @param floodplain The plain to flood.
 * @param height The water height, in meters.
 * @return A Grid indicating which cells are flooded.
 */
Grid<bool> simulateFlood(const Floodplain& floodplain, double height);

#endif
